name: UltimateHammer
main: com.elikill58.ultimatehammer.UltimateHammer
version: 1.4
author: Elikill58
api-version: 1.13

softdepend: [WorldGuard, Factions]

commands:
  ultimatehammer:
    aliases: [hammer, uh]