apply plugin: 'eclipse'

eclipse {
    project {
        name = 'UHv2-aureliumskills'
    }
}

evaluationDependsOn(':spigot')

sourceSets {
    main {
        java.srcDirs = ['src']
        resources.srcDirs = ['resources']
    }
}

repositories {
    maven {
        url 'https://jitpack.io'
    }
}


dependencies {
    compileOnly 'com.github.Archy-X:AuraSkills:2.1.5'
    api(project(':spigot'))
    compileOnly(project(path: ':spigot', configuration: 'spigot'))
}