name: "Something else"
description: "Something not listed here"
title: "Other: "
labels: []
assignees: []
body:
- type: markdown
  attributes:
    value: "Use this template only if others are not available for your"
- type: checkboxes
  id: versions
  attributes:
    label: "Are you using v2 (premium) ?"
    options:
      - label: "Yes I bought UltimateHammer V2"
- type: textarea
  id: explaination
  attributes:
    label: "Explain everything"
    description: "Why are you creating an issue ? Explain with more details as possible"
  validations:
    required: true
