name: UltimateHammer
main: com.elikill58.ultimatehammer.spigot.SpigotUltimateHammer
version: ${version}
author: Elikill58
api-version: 1.13

softdepend: [WorldGuard, Factions, Quests, AureliumSkills, Slimefun]

commands:
  ultimatehammer:
    aliases: [hammer, uh]