###################################################################
#                                                                 #
#                  UltimateHammer by Elikill58                    #
#                                                                 #
#              If you have a problem or a suggestion,             #
#                    You can contact me on:                       #
#                  - Discord: @Elikill58#0743                     #
#       - my Discord server: https://discord.gg/KHRVTX2           #
#               - Mail: arpetzouille@gmail.com                    #
#                   - SpigotMC: Elikill58                         #
#                  - Minecraft.fr: Elikill                        #
#                                                                 #
###################################################################

items:
  # This is an example of an item
  example-item:
    enable: false
    available-types:
    - "hammer: Destroy 3x3x1 according to your vision"
    - "axe: Destroy a complete tree"
    - "hoe: automatically plant seed from your inventory"
    - "infinite: An infinite item which stay on your inventory, even after a death"
    type:
    - "hammer"
    # Set "" if you want to disable it
    message: "&eThis is the &cHammer &e!"
    # permission to use it. Set "" to allow everyone to use it
    permission: "ultimatehammer.hammer"
    material: "DIAMOND_PICKAXE"
    # Optional. Default: 1
    amount: 1
    # Optional. Default: basic MC name
    name: "-"
    # Optional. Default: nothing
    lore:
    - ""
    # Optional. Default: any
    enchant:
    - "DAMAGE_ALL"
    - "PROTECTION_ENVIRONMENTAL:2"
    # All blocks that will NOT be destroyed by the hammer
    blacklist:
    - "MOB_SPAWNER"
    - "CHEST"

  # Destroy 3x3x1 according to your vision
  hammer:
    enable: true
    type:
    - "hammer"
    message: "&eThis is the &cHammer &e!"
    permission: "ultimatehammer.hammer"
    material: "DIAMOND_PICKAXE"
    amount: 1
    name: "&b&k-&r &cHammer &b&k-"
    hammer:
      blacklist:
      - "MOB_SPAWNER"
      - "CHEST"
      size: 3
      layer: 1

  # Destroy all of a tree
  axe:
    enable: true
    type:
    - "axe"
    message: "&eThis is the &cAxe &e!"
    permission: "ultimatehammer.axe"
    material: "DIAMOND_AXE"
    name: "&aTree destroyer"

  # Automatic plant a seed which is on your inventory
  hoe:
    enable: true
    type:
    - "hoe"
    message: "&eThis is the &cHoe &e!"
    permission: "ultimatehammer.hoe"
    material: "DIAMOND_HOE"
    name: "&cThe ultimate HOE"
    hoe:
      size: 3

  # Keep on inventory on death
  sword:
    enable: true
    type:
    - "infinite"
    message: "&eThis is the &cinfinite sword &e!"
    permission: "ultimatehammer.hoe"
    material: "DIAMOND_SWORD"
    name: "&cInfinite sword"

  all:
    enable: true
    type:
    - "hammer"
    - "hoe"
    - "axe"
    - "infinite"
    message: "&4&l>> &6&lUltimate Hammer &7: &cCan do everything &4&l<<"
    permission: "ultimatehammer.all"
    material: "STICK"
    name: "&cThe &4Ultimate &c&lHammer"
    lore:
    - "&7This stick can:"
    - "Break 3x3"
    - "Destroy tree"
    - "Plant seed"
    - "Stay with you after respawn"

region-bypass:
  enabled: false
  1:
    # You need WorldGuard for the region
    regions:
    - "spawn"
    # Default worlds names (or Multiverse names)
    worlds:
    - "world_the_end"
    # the feature disabled (sword/hoe...)
    features:
    - "hoe"

Database:
  isActive: false
  # To get the information. We use the player uuid to get the information.
  # We get only what you write. We never add or remove something.
  # We don't save your private information about your database
  url: "127.0.0.1/myDb"
  user: root
  password: "myPassword"
  type: "mysql"

# Configuration of the permissions subsystem. For more information
# see https://github.com/Elikill58/UltimateHammer/wiki/Permissions
Permissions:
  # The checker indicates if a player has a specific permission.
  # By default only 'platform' is available
  checker: platform
  check:
    default: "negativity.check"

Translation:
  active: false # enable or disable the translation
  lang_available:
  - en_US
  - fr_FR
  default: en_US
  # The provider used to get translated messages, useful if you want to customize the way UltimateHammer gets its messages.
  # The only one available out-of-the-box is "platform".
  provider: platform

# Accounts hold player-specific data of the plugin, like their language and alerts count.
accounts:
  storage:
    # The ID of the storage to use.
    #
    # The following are available out-of-the-box:
    # - file : stored in files under ./plugins/UltimateHammer/user/
    # - database : uses a database
    # Defaults to "file"
    id: "file"
